export const data = [
  { label: 'rice', value: '1' },
  { label: 'maize', value: '2' },
  { label: 'chickpea', value: '3' },
  { label: 'kidneybeans', value: '4' },
  { label: 'pigeonpeas', value: '5' },
  { label: 'mothbeans', value: '6' },
  { label: 'mungbean', value: '7' },
  { label: 'blackgram', value: '8' },
  { label: 'lentil', value: '9' },
  { label: 'pomegranate', value: '10' },
  { label: 'banana', value: '11' },
  { label: 'mango', value: '12' },
  { label: 'grapes', value: '13' },
  { label: 'watermelon', value: '14' },
  { label: 'muskmelon', value: '15' },
  { label: 'apple', value: '16' },
  { label: 'orange', value: '17' },
  { label: 'papaya', value: '18' },
  { label: 'coconut', value: '19' },
  { label: 'cotton', value: '20' },
  { label: 'jute', value: '21' },
  { label: 'coffee', value: '22' },
];